### ISSUE TITLE
¿Cómo los has descargado y qué frecuencia de actualización prevés?

### ISSUE THREAD

**Issue by nacholopex** [JaimeObregon/twitter_instituciones#1]
Muy buenas Jaime👋🏼.
Para realizar estos archivos ¿has usado la API que facilita twitter o has realizado un scrapping a cada una de las cuentas? ¿Con qué frecuencia estos datos se actualizarán? 🕐 💻

**Comment by JaimeObregon** [comment]
Hola, @nacholopex. Los tuits los he descargado con [Twint](https://github.com/twintproject/twint). En cuanto a la actualización: no es mi intención actualizar el archivo. O, al menos, no es hacerlo con frecuencia. Lo que he querido es descargar todos los tuits de la última década (aproximadamente) para poder trabajar con software sobre ellos. Si te animas con esto último, házmelo saber. 😉 

Cierro este issue porque lo doy por respondido. Pero siéntete libre de reabrirlo si tienes alguna otra pregunta.
