### ISSUE TITLE
Tweets ayuntamiento de Madrid

### ISSUE THREAD

**Issue by MiguelPerezCerdan** [JaimeObregon/twitter_instituciones#2]
Buenas, 

Antes de nada, darte las gracias por este repositorio que nos has brindado. 

Me gustaría a ver si fuera posible conseguir los tweets de la cuenta institucional del Ayuntamiento de Madrid (https://twitter.com/MADRID?s=20)

Muchas gracias!!

**Comment by JaimeObregon** [comment]
Hola, @MiguelPerezCerdan. Recibido; los estoy descargando y los subiré en un rato, si todo va bien.
